import React from "react";
import Head from "next/head";
import Header from "./Header";
import { motion } from "framer-motion";

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>NodeSend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 min-h-screen">
        <div className="container mx-auto">
          <Header />
          <motion.main 
            initial={{x: '-100vw'}}
            animate={{x: 0}}
            transition={{type: 'spring', duration: 1, bounce: 0.3}}
            className="mx-20">
            {children}
          </motion.main>
        </div>
      </div>
    </>
  )
}

export default Layout